### PR TITLE
Feature/mac retina fix

### PR DESCRIPTION
**Pull request by papagiannakis**
@kamarianakis @stratosger please check on macos and windows if my fix on basicCubeGUI is ok on your end. On high retina displays I was getting miniscule ImGUI windows + I could not move them around. 
Also I removed tracking of the generated executables and libs on macos

### CODE REVIEW

**Comment by stratosger** [comment]
On my mac it worked fine. On Windows though, the two GUIs appear on top of each other in the beginning. If @kamarianakis is also ok with it then its good for me.

**Comment by kamarianakis** [comment]
the difference i am spoting between current dev and feature is that i can now move the gui freely, before it was fixed. (I also notice that when switching between dev and feature branch, it asks me to delete the untracked imgui.ini as it will be replaced, meaning it is generated in the one branch and on the other it is stored). LGTM.

**Comment by kamarianakis** [comment]
> On my mac it worked fine. On Windows though, the two GUIs appear on top of each other in the beginning. If @kamarianakis is also ok with it then its good for me.

I also have the same "problem". Initially, the two guis over collapse.

**Comment by papagiannakis** [comment]
it saves a local .ini file with last positions so that when you restart is ok. I guess it is ok when you move them around. main update is in the constructor of sdl2 window to allow for highDPI screens. if on  are ok, pleas replicate these for all projects.

**Review by kamarianakis — APPROVED** [review]

**Pull request closed without merging**
